### PR TITLE
TEPHRA-208 Compaction removes rows incorrectly for family deletes wit…

### PR DESCRIPTION
**Pull request by twdsilva**
…h column level conflict detection

@poornachandra  @gokulavasan

### CODE REVIEW

**Comment by twdsilva** [comment]
I'm not sure why the test is failing for the hbase 1.2 cdh version. I will look into it.

**Comment by twdsilva** [comment]
testFamilyDeleteWithCompaction() fails for the hbase 1.2 cdh version because HDFSTransactionStateStorage cannot be initialized as it can't find the snapshot directory in config, however this test passes in the other hbase versions. 

@poornachandra  Any idea what could be happening here?
```
2017-01-12 11:00:14,329 - ERROR [HDFSTransactionStateStorage STARTING:o.a.z.s.NIOServerCnxnFactory$1@44] - Thread Thread[HDFSTransactionStateStorage STARTING,5,main] died
java.lang.IllegalStateException: Snapshot directory is not configured.  Please set data.tx.snapshot.dir in configuration.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149) ~[guava-13.0.1.jar:na]
	at org.apache.tephra.persist.HDFSTransactionStateStorage.startUp(HDFSTransactionStateStorage.java:94) ~[tephra-core-0.11.0-incubating-SNAPSHOT.jar:0.11.0-incubating-SNAPSHOT]
	at com.google.common.util.concurrent.AbstractIdleService$1$1.run(AbstractIdleService.java:43) ~[guava-13.0.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_76]
```

**Comment by gokulavasan** [comment]
@twdsilva Curious why we need to use HDFSTransactionStateStorage to test this? Is there any problem with running it with the existing InMemoryTransactionStateStorage?

**Comment by twdsilva** [comment]
Compaction wasn't removing deleted rows when InMemoryTransactionStateStorage() was used. I think this had something to do with how visibilityUpperBound was set in IncludeInProgressFilter based on the txn snapshot.

**Comment by gokulavasan** [comment]
oh yes that is right. my bad. thanks for the clarification @twdsilva

**Comment by poornachandra** [comment]
@twdsilva Some code changes have not been ported over to file tephra-hbase-compat-1.1-base/src/test/java/org/apache/tephra/hbase/TransactionAwareHTableTest.java, hence the tests are failing. For instance, HDFSTransactionStateStorage is not initialized and miniDFS cluster is not started in that file.

**Comment by twdsilva** [comment]
@gokulavasan , thanks.  I have fixed the issue and the tests pass now.

**Comment by poornachandra** [comment]
@twdsilva The changes look good. However, we recently did a re-factoring of TransactionAwareHTableTest by moving mini cluster startup/shutdown to a base class AbstractHBaseTableTest. It would be good if non-Transaction Manager startup/shutdown code and configuration setup in this PR are moved to AbstractHBaseTableTest.

**Comment by twdsilva** [comment]
@poornachandra  Thanks for the review. I have made the change.

**Comment by gokulavasan** [comment]
@twdsilva Couple of comments:
i) It would be good to make changes to only  one compat-module and then open it for review and once the comments are addressed and changes look good, you can then proceed to port it to other modules and get a final lgtm before merging. That way you don't have to address changes in all compat modules everytime

ii) I think what @poornachandra meant was, we currently start the miniCluster in AbstractHBaseTableTest. And so we can move the code where you start the MiniDFSCluster to AbstractHBaseTableTest#startMiniCluster method.

**Comment by twdsilva** [comment]
@gokulavasan I didn't move the MiniDFSCluster initialization into AbstractHBaseTableTest since the other tests that extend AbstractHBaseTableTest didn't require staring the MiniDFSCluster.

**Comment by gokulavasan** [comment]
@poornachandra Do you have any thoughts on https://github.com/apache/incubator-tephra/pull/26#issuecomment-276127210 ?

**Comment by poornachandra** [comment]
I think that is fine. LGTM. Thanks for the fix @twdsilva!

**Pull request closed without merging**
