### PR TITLE
TEPHRA-206 Port Invalid list pruning changes to other hbase compat modules

### PR DESCRIPTION
**Pull request by gokulavasan**
JIRA : https://issues.apache.org/jira/browse/TEPHRA-206

### CODE REVIEW

**Comment by poornachandra** [comment]
@gokulavasan https://github.com/apache/incubator-tephra/pull/22 is now merged, please include changes from that PR too

**Comment by gokulavasan** [comment]
@poornachandra Can you review the commit (https://github.com/apache/incubator-tephra/pull/25/commits/3db422bc73fd3aeb75e36b050b710bf1af15f22e) where I have ported the changes from PR#22. I am porting changes to other compat modules as well.

**Comment by gokulavasan** [comment]
@poornachandra Ported changes from PR#22 to all compat modules. Please review PR when you get a chance. Thanks!

**Comment by poornachandra** [comment]
LGTM

**Pull request closed without merging**
